```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  .col4 {
    columns: 4 100px;         / number of columns and width in pixels/
    -webkit-columns: 4 200px; / chrome, safari /
    -moz-columns: 4 200px;    / firefox /
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

<br/>

## Data
<br/>

<div class="col3">

Statsbomb: [1](https://statsbomb.com/resource-centre/) | [2](https://github.com/FCrSTATS/StatsBomb_WomensData) | [3](https://github.com/statsbomb/StatsBombR) | [4](https://github.com/FCrSTATS/SBpitch/blob/master/README.md)

WC 2018: [1](https://gitlab.com/djh_or/2018-world-cup-stats) | [2](https://github.com/2622NSW/FIFAplayertracking18/blob/master/20180614_01_Russia_SaudiArabia.pdf)

[Opta Data Schema](http://www.soccermetrics.net/match-data-collection/the-opta-data-schema-an-introduction)

[Opta Event Definitions](http://optasports.com/news-area/blog-optas-event-definitions.aspx)

[Query F24 Data](https://github.com/huffyhenry/ltl24)

[Beginner's Guide](https://sportsdatachallenge.wordpress.com/2016/09/21/a-total-beginners-guide-to-web-scraping-football-data-part-1/)

[Radar API](http://developer.sportradar.com/files/indexSoccer.html#soccer-api-v3)

[Whoscored Scraper](https://github.com/brianlan/Whoscored/blob/master/crawl_player_match_level_data.py)

[World Football](http://usa.worldfootball.net/) | http://www.rsssf.com/

[Kaggle](https://www.kaggle.com/hugomathien/soccer)

[Soccermetrics Projects](https://github.com/soccermetrics/project-data)

[Football KPI's](https://github.com/teouch/fbl-kpis)

Betting: [1](http://www.football-data.co.uk/downloadm.php) | [2](https://boggio-analytics.com/fp-api/)

[Open Football](https://github.com/openfootball)

[JSON European Data](https://github.com/opendatajson/football.json)

[International Data](https://github.com/SoccerStatsUS/international_data/tree/master/games)

Historical Results: [1](https://github.com/jalapic/engsoccerdata) | [2](https://github.com/footballcsv/eng-england) | [3](https://github.com/hugomathien/football-data-collection)| [4](https://github.com/llimllib/soccerdata)

Wide Collections: [1](https://github.com/jokecamp/FootballData) | [2](https://github.com/octonion/soccer) | [3](https://github.com/octonion/soccer-private) | [4](https://www.jokecamp.com/blog/guide-to-football-and-soccer-data-and-apis/)
</div>
<br/>

## Toolbox
<br/>

<div class="col3">
[Performance Analysis](http://thevideoanalyst.com/want-performance-analyst/)

[Tavares](https://github.com/rjtavares/football-crunching)

https://github.com/Torvaney/ggsoccer

https://github.com/ryurko/fcscrapR

https://fcpython.com/

[xG Model](https://github.com/KubaMichalczyk/ExpectedGoalsModel/blob/master/expected_goals_model.md)

[Comprehensive Overview](https://oneshortcorner.wordpress.com/2016/11/03/football-analytics-part-seven-how-not-to-use-stats/)

[Stats & Sports Class](https://statsbylopez.com/stats-sports-class/)

[STATS Data Science](https://www.stats.com/data-science/)

[ML For Sports](https://dtai.cs.kuleuven.be/events/MLSA16/schedule.php)

[Toolbox Overview](http://statsbomb.com/2016/09/a-toolbox-for-football-analytics/)

[Analysis Pipeline](https://teouchanalytics.wordpress.com/2017/07/08/episode-1-feature-engineering-and-some-data-to-play-with/)

[Working With Play By Play Data](http://curleylab.psych.columbia.edu/playbyplay/playbyplay.html#/)

[Swarm Plots](http://pena.lt/y/2017/07/17/radar-alternatives-football-data/)

https://github.com/KubaMichalczyk/Tracking-Data/blob/master/convex_hull_animation.R

## Projects
<br/>

<div class="col3">
[Crosses In Scipy](https://twitter.com/Samirak93/status/905107479880581120)

[XG Simulator](https://torvaney.github.io/projects/xG.html)

https://github.com/huffyhenry/dixon-coles-worldcup

https://twelve.football/analytics

https://trinket.io/glowscript/57ec47ae64

[Positional Data Visualization](https://github.com/JoGall/soccermatics)

[EPL Chances](https://public.tableau.com/profile/scribblr.42#!/vizhome/ChancesDashboard2017-18-PoweredbyStrataBet/PremierLeagueChances2016-17?publish=yes)

[Goals From Corners](https://www.reddit.com/r/soccer/comments/6nuk85/so_ive_scraped_statistics_for_about_11000_matches/)

Objective Football: [1](https://objective-football.blogspot.co.uk/2016/08/201617-shots-in-box.html?m=1) | [2](https://objective-football.blogspot.co.uk/2016/08/201617-open-playset-piecepenalty-data.html?m=1)

[Player Tracking](https://samirak93.wordpress.com/2016/01/05/player-tracking-using-corel-video-studio/)

[Chalkboard](https://github.com/neilcharles/chalkboard)

https://mytinyshinys.shinyapps.io/premierLeague/

http://canntable.com

http://statszone.tiki-taka.co/

https://twitter.com/SportsDataChal/status/740675516093566980

[South American WC Qualifiers](https://public.tableau.com/profile/mathijs.steneker#!/vizhome/xGmapeliminatorias/Matchstats)

[Pitch Tracker](http://johnburnmurdoch.github.io/football-pitch-tracker/)

[Tableau Dashboards](https://differentgame.wordpress.com/xg-shot-maps-and-tables/)

[xG Shot Maps](https://public.tableau.com/s/profile/paul.riley#!/vizhome/PremierLeague201516xGMap/PremierLeague201516ShotonTargetxGDashboard)

[xG Calculator](https://dannypage.github.io/expected_goals.html)

[Analysts Table](https://hilltop-analytics.shinyapps.io/Analysts-EPL-Table/)

[Bet Bot](http://www.betbot.soccer/)

[AVIZ Visualization](http://www.aviz.fr/soccer)

[Bayesian Modeling](https://github.com/milkha/EPL_KDD)

[Unlucky Arsenal](https://github.com/Torvaney/unlucky-arsenal)

[Optapro Forum](http://www.optasportspro.com/about/optapro-blog/?tag=Analytics%20Forum)

[Soccermetrics Collaboration](http://www.soccermetrics.net/collaborations/research-collaborations-2017)

[Stats Collection In Women's Soccer](https://wosostats.wordpress.com/how-to-help)
</div>
<br/>

## Metrics

<br/>

<div class="col3">
[Ranked Probability Score](https://cognitivefootball.wordpress.com/rps/)

[Shapely Values](https://github.com/pfletcherhill/ShapleySoccer)

[Goal Gravity](http://business-analytic.co.uk/blog/gravity-part-1-a-metric-for-event-importance/)

[Expected Assists](http://www.optasportspro.com/about/optapro-blog/posts/2017/blog-expected-assists-in-context/)

Pythagorean Expectation: [For](http://statsbomb.com/2016/04/improving-soccers-version-of-the-bill-james-pythagorean/) | [Against](http://www.soccermetrics.net/soccer-pythagorean-theory/why-the-baseball-pythagorean-doesnt-work-for-soccer)

[Team Defensive Metrics](http://business-analytic.co.uk/blog/uncategorized/team-defensive-metrics/)

[Possession's Framework](http://www.optasportspro.com/about/optapro-blog/posts/2016/blog-introducing-a-possessions-framework/)

[Expected Saves](http://www.soccermetrics.net/goalkeeping-analytics/expected-saves-an-inverse-of-expected-goals)

[Bayesian Player Ratings](http://pena.lt/y/2015/02/26/playerrating-a-bayesian-method-for-evaluating-football-players/)

Possession: [1](https://2plus2equals11.com/2015/08/25/valuing-possession/) | [2](http://www.worldfootballcommentaries.com/2013/02/possession-efficiency-ratio-new.html)

[Total Shots Ratio](https://jameswgrayson.wordpress.com/2012/07/15/another-post-about-tsr/)

[Dribbling](http://www.optasportspro.com/about/optapro-blog/posts/2016/blog-carry-on-dribbling/)

[xG](http://cartilagefreecaptain.sbnation.com/2015/10/19/9295905/premier-league-projections-and-new-expected-goals)

Usage Rates: [1](http://regressing.deadspin.com/stat-primer-what-can-usage-rates-teach-us-about-the-pr-1642456897) | [2](http://tempofreesoccer.blogspot.co.uk/2014/09/usage-rates-primer.html)

[Attacking Contribution](http://statsbomb.com/2014/10/attacking-contribution-metric-and-man-uniteds-reliance-on-di-maria/)

[Chances Created](http://statsbomb.com/2014/07/what-matters-in-football-a-deeper-look-at-chances-created/)

[High Press](http://statsbomb.com/2014/07/defensive-metrics-measuring-the-intensity-of-a-high-press/)

[Attacking Speed](http://statsbomb.com/2014/06/the-importance-of-attacking-speed-and-the-quickest-attacking-team-in-epl/)

[Defensive Efficiency](https://thecounterattack.wordpress.com/2013/02/20/measuring-defensive-efficiency-deff/)

[PDO](https://jameswgrayson.wordpress.com/2011/04/05/pdo-part-i/)

[Team Ratings](https://jameswgrayson.wordpress.com/2014/08/11/methodology-and-validation-of-the-team-ratings/)

[Attacking Effectiveness](http://experimental361.com/2013/01/21/attacking-effectiveness-europe/)

[Game States](http://11tegen11.net/2013/04/06/game-states-and-conversion/)

[Gaussian Metrics](http://analyticsfc.co.uk/2015/12/03/joydivisualization-comparing-individual-performance-to-the-population/)

[Pythagorean Wins](https://www.reddit.com/r/soccer/comments/4dmdlq/oc_pythagorean_wins_expectation_for_the_premier/)
</div>
<br/>

## Cribsheet
<br/>

* Soccer matches modeled by Poisson distribution: goals_soccer ~ poisson(lambda = 1.4)

* Average percentage of goalscoring shots on target taken that end up as goals: 31%. 

* Average percentage of goalscoring shots on target taken that end up as goals: 10.5% (Anything outside 7-12% will pretty much certainly not last - eventually)

* Shots: At least 3.5 shots per 90 is typically good. Over 4 or 4.5 is pushing toward elite.

* Previous research shows that a shot without defenders between the goal and ball goes in 11.59% on average vs 7.49% if defenders are present.

* A fairly simple guideline for non-penalty scoring rates as a Forward:

    * .4 to .49 non-penalty goals per 90: Good.
    * .5 to .59 non-penalty goals per 90: Very good.
    * .6 to .79 non-penalty goals per 90: Probable Top 20 in Europe
    * .8 or above non-penalty goals per 90: Probable Top 5 in Europe