---
title: "Other Resources"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Other

http://business-analytic.co.uk/blog/uncategorized/team-defensive-metrics/

https://www.youtube.com/user/optasports/videos

The sports data API is a service we provide to the community because we have this data and we were fortunate enough to negotiate a deal with Sportradar who agreed that making a non-commercial license available to fans was a great idea. That’s the API. We built a bunch of utilities on top of their data to speed access and organize data in the way we know fans think. We never wanted to make any money selling this data. That’s Sportradar’s business.

NOTES

https://github.com/hugomathien/football-data-collection

https://github.com/neilcharles/chalkboard

https://github.com/huffyhenry/ltl24

pythagorean expectation

Strategical aspect in football I never see anyone talk about are connections between players. How connected is a team? How much space do they occupy while being connected? When do they lose them? What are they doing against opp. connections? This applies to defense and offense.

PDO: 100*(shooting %+save %): 1000 avg. A blogger points out that the team has a likely un-sustainably high PDO.

TSR: shots for(shots for + shots against)

Expected goals is a rough measurement of how many goals an average player is expected to score from a set of scoring chances. Weighed against years of 
historical data, ExG takes into account the position and context of each shot and assigns a goal-scoring probability to each opportunity.

Average percentage of goalscoring shots on target taken that end up as goals: 31%. 

Average percentage of goalscoring shots on target taken that end up as goals: 10.5% (Anything outside 7-12% will pretty much certainly not last - eventually)

Shots: >= 3.5 shots per 90 is typically good, over 4 or 4.5 is pushing toward elite. 

Previous research shows that a shot without defenders between the goal and ball goes in 11.59% on average vs 7.49% if defenders are present.

A fairly simple guideline for non-penalty scoring rates as a Forward is as follows:

.4 to .49 non-penalty goals per 90: Good.
.5 to .59 non-penalty goals per 90: Very good.
.6 to .79 non-penalty goals per 90: Probable Top 20 in Europe
.8 or above non-penalty goals per 90: Probable Top 5 in Europe

Say something meaningful.

http://www.aviz.fr/soccer

NBA SportVU data

https://objective-football.blogspot.co.uk/2016/08/201617-shots-in-box.html?m=1

https://objective-football.blogspot.co.uk/2016/08/201617-open-playset-piecepenalty-data.html?m=1

http://opisthokonta.net/?p=1548

https://deepxg.com/2016/12/31/state-of-the-stats-2016-results/

https://twitter.com/FanalyticsBlogs

https://www.youtube.com/user/footballemporium/playlists

http://www.unravelsports.com/pex/

http://www.dailymotion.com/video/x2iku17

http://footballia.net/

https://iwringer.wordpress.com/2014/06/20/glimpse-of-the-future-overlaying-realtime-analytics-on-football-broadcasts/

https://samirak93.wordpress.com/2016/01/05/player-tracking-using-corel-video-studio/

http://statsbomb.com/2016/09/a-toolbox-for-football-analytics/

[Spielverlagerung](http://spielverlagerung.com/)

http://analysport.fr/atletico-madrid-en/

https://twitter.com/zorba138/status/752132960221073408

https://twitter.com/StatsbyLopez/status/796014026094481408

https://dtai.cs.kuleuven.be/events/MLSA16/schedule.php

http://thevideoanalyst.com/want-performance-analyst/

https://github.com/soccermetrics/project-data

##Blogs

[OnsideFC](https://github.com/OnsideFC)

[sporting logic](https://sportinglogicblog.wordpress.com)

[murdock](http://johnburnmurdoch.github.io/)

Northyard Analytics

[Analytics FC](http://analyticsfc.co.uk)

[Outsiders In](https://outsidersin.wordpress.com/)

[Football Facts](http://www.myfootballfacts.com/)

[Yuan](http://andrewyuan.github.io)

[DG](https://differentgame.wordpress.com/)

[GoalPower](http://thepowerofgoals.blogspot.co.uk)

[Jalapic](http://jalapic.github.io/)

[Stoppage Time](http://5addedminutes.com)

[Grayson](https://jameswgrayson.wordpress.com)

[WoSo](https://wosostats.wordpress.com/)

[Objective](http://objective-football.blogspot.com.es)

[11](https://2plus2equals11.wordpress.com)

[Snakeoil](http://statsandsnakeoil.wordpress.com)

[BG](http://www.bootifulgame.com)

[Fog](http://www.wallpaperingfog.co.uk)

[Page](http://dannypage.github.io/)

[Martin Eastwood]([https://github.com/martineastwood/penalty)

[Tavares](https://github.com/rjtavares/football-crunching)

[Opta](http://www.optasportspro.com/about/interesting-links.aspx)

http://theopenfootball.blogspot.co.uk/

##Twitter

https://twitter.com/neilcharles_uk/lists/football-analysis

https://twitter.com/centralwinger/lists/soccer-analytics