---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

#### General

[Opta Data Schema](http://www.soccermetrics.net/match-data-collection/the-opta-data-schema-an-introduction)

[Opta Event Definitions](http://optasports.com/news-area/blog-optas-event-definitions.aspx)

#### Technical

Coding, scraping, or calling APIs.

[Query F24 Data](https://github.com/huffyhenry/ltl24)

[Beginner's Guide](https://sportsdatachallenge.wordpress.com/2016/09/21/a-total-beginners-guide-to-web-scraping-football-data-part-1/)

[Radar API](http://developer.sportradar.com/files/indexSoccer.html#soccer-api-v3)

[Whoscored Scraper](https://github.com/brianlan/Whoscored/blob/master/crawl_player_match_level_data.py)

[World Football](http://usa.worldfootball.net/)

[Data Collection](https://github.com/hugomathien/football-data-collection)

[Kaggle](https://www.kaggle.com/hugomathien/soccer)

#### Non-Technical

CSV's or json readily available.

[Soccermetrics Projects](https://github.com/soccermetrics/project-data)

[Football KPI's](https://github.com/teouch/fbl-kpis)

[Football Data UK](http://www.football-data.co.uk/downloadm.php)

[Open Football](https://github.com/openfootball)

[Historical Scorelines](https://github.com/llimllib/soccerdata)

[World Cup Data](https://github.com/sanand0/fifadata)

[Football Data UK](http://www.football-data.co.uk/data.php)

[JSON European Data](https://github.com/opendatajson/football.json)

[International Data](https://github.com/SoccerStatsUS/international_data/tree/master/games)

Historical Results::[1](https://github.com/jalapic/engsoccerdata):[2](https://github.com/footballcsv/eng-england)

Wide Collections::[1](https://github.com/jokecamp/FootballData):[2](https://github.com/octonion/soccer)

## Analysis Toolbox

[Performance Analysis](http://thevideoanalyst.com/want-performance-analyst/)

[Comprehensive Overview](https://oneshortcorner.wordpress.com/2016/11/03/football-analytics-part-seven-how-not-to-use-stats/)

[Stats & Sports Class](https://statsbylopez.com/stats-sports-class/)

[STATS Data Science](https://www.stats.com/data-science/)

[ML For Sports](https://dtai.cs.kuleuven.be/events/MLSA16/schedule.php)

[State of the Stats: 2016](https://deepxg.com/2016/12/31/state-of-the-stats-2016-results/)

[RStats Libraries](https://twitter.com/StatsbyLopez/status/796014026094481408)

[Toolbox Overview](http://statsbomb.com/2016/09/a-toolbox-for-football-analytics/)

[Analysis Pipeline](https://teouchanalytics.wordpress.com/2017/07/08/episode-1-feature-engineering-and-some-data-to-play-with/)

[Working With Play By Play Data](http://curleylab.psych.columbia.edu/playbyplay/playbyplay.html#/)

[Swarm Plots](http://pena.lt/y/2017/07/17/radar-alternatives-football-data/)

## Projects

#### Reference

[Crosses In Scipy](https://twitter.com/Samirak93/status/905107479880581120)

[Goals From Corners](https://www.reddit.com/r/soccer/comments/6nuk85/so_ive_scraped_statistics_for_about_11000_matches/)

Objective Football::[1](https://objective-football.blogspot.co.uk/2016/08/201617-shots-in-box.html?m=1):[2](https://objective-football.blogspot.co.uk/2016/08/201617-open-playset-piecepenalty-data.html?m=1)

[Player Tracking](https://samirak93.wordpress.com/2016/01/05/player-tracking-using-corel-video-studio/)

[Chalkboard](https://github.com/neilcharles/chalkboard)

[South American WC Qualifiers](https://public.tableau.com/profile/mathijs.steneker#!/vizhome/xGmapeliminatorias/Matchstats)

[Pitch Tracker](http://johnburnmurdoch.github.io/football-pitch-tracker/)

[Tableau Dashboards](https://differentgame.wordpress.com/xg-shot-maps-and-tables/)

[xG Shot Maps](https://public.tableau.com/s/profile/paul.riley#!/vizhome/PremierLeague201516xGMap/PremierLeague201516ShotonTargetxGDashboard)

[xG Calculator](https://dannypage.github.io/expected_goals.html)

[Analysts Table](https://hilltop-analytics.shinyapps.io/Analysts-EPL-Table/)

[Bet Bot](http://www.betbot.soccer/)

[AVIZ Visualization](http://www.aviz.fr/soccer)

[Bayesian Modeling](https://github.com/milkha/EPL_KDD)

[Unlucky Arsenal](https://github.com/Torvaney/unlucky-arsenal)

#### Ideas

[Soccermetrics Collaboration](http://www.soccermetrics.net/collaborations/research-collaborations-2017)

[Stats Collection In Women's Soccer](https://wosostats.wordpress.com/how-to-help)

## Cribsheet

* Average percentage of goalscoring shots on target taken that end up as goals: 31%. 

* Average percentage of goalscoring shots on target taken that end up as goals: 10.5% (Anything outside 7-12% will pretty much certainly not last - eventually)

* Shots: At least 3.5 shots per 90 is typically good. Over 4 or 4.5 is pushing toward elite.

* Previous research shows that a shot without defenders between the goal and ball goes in 11.59% on average vs 7.49% if defenders are present.

* A fairly simple guideline for non-penalty scoring rates as a Forward:

    * .4 to .49 non-penalty goals per 90: Good.
    * .5 to .59 non-penalty goals per 90: Very good.
    * .6 to .79 non-penalty goals per 90: Probable Top 20 in Europe
    * .8 or above non-penalty goals per 90: Probable Top 5 in Europe
